### ISSUE TITLE
New (or no) captcha

### ISSUE THREAD

**Issue by dostro** [dfinity/wg-identity-authentication#4]
The problem:
A substantial number of users have been complaining about the captcha working unreliably on first attempt. Also people hate captchas.

Discussion suggestions:
- Improve first-use reliability
- More user-friendly captcha than text input
- Implement [private access tokens](https://www.ietf.org/archive/id/draft-private-access-tokens-01.html) so that users on supported devices/browsers won't need a captcha at all

**Comment by frederikrothenberger** [comment]
Hi @dostro 

Thanks for raising this issue. The captcha served by II seems to me to be an II-specific issue that is better addressed in the II repository directly instead of the working group (which deals with IC platform related questions).

Moving the discussion here: https://github.com/dfinity/internet-identity/issues/914
